---
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: backend-secrets
  namespace: backend
spec:
  provider: aws
  secretObjects:
    - secretName: backend-secrets
      type: Opaque
      data:
        - objectName: db_username
          key: db_username
        - objectName: db_password
          key: db_password
  parameters:
    objects: |
      - objectName: "<DB_SECRET_NAME>"
        objectType: "secretsmanager"
        jmesPath:
          - path: "username"
            objectAlias: "db_username"
          - path: "password"
            objectAlias: "db_password"
